### ISSUE TITLE
PDOException query was empty error

### ISSUE THREAD

**Issue by vaidyamanishjoshi** [bennettstone/SimplePDO#1]
I am using your SimplePDO wrapper class. I am getting following error :

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty' in C:\xampp\htdocs\mysite\include\SimplePDO.php:200 Stack trace: #0 C:\xampp\htdocs\mysite\include\SimplePDO.php(200): PDO->prepare('') #1 C:\xampp\htdocs\mysite\include\SimplePDO.php(244): SimplePDO->query(false, Array, true) #2 C:\xampp\htdocs\mysite\articles.php(57): SimplePDO->get_results(false) #3 {main} thrown in C:\xampp\htdocs\mysite\include\SimplePDO.php on line 200

Using code is as follows :

$q1 = $database1->query( "SELECT * FROM sa_articleuploads_by_admin WHERE language=? ORDER BY article_upload_date AND article_subject ASC ", array( 'marathi' ));
$objTotalRS1 = $database1->get_results( $q1 );
$counts = 1;
$len = $database1->num_rows( $q1 );

if ($len !=0){
  foreach ($objTotalRS1 as $data){
    ......////rest of my code

**Comment by bennettstone** [comment]
That's because your query should be:
```php
$objTotalRS1 = $database1->get_results( "SELECT * FROM sa_articleuploads_by_admin WHERE language=? ORDER BY article_upload_date AND article_subject ASC ", array( 'marathi' ) );
```
